### ISSUE TITLE
[Feature Request] Any way to block NPC yell messages with this addon?

### ISSUE THREAD

**Issue by EyeOfTheBeast** [Lexiebean/TurtleHCFilter#1]
Some examples of NPCs that yell spam a lot, cluttering up the chat box:

- Marlos Catos Shellcoin yells in Stormwind
- Reginald Windsor related yells when someone is doing the Onyxia attunement quest line in Stormwind
- Tansy Sparkpen yells about selling the Gadgetzan Times in Stormwind

I find all of these NPC's yells to be cluttering up the chat box every day when in Stormwind, is it possible for this addon to move these NPC's yells to another chat channel as well?

**Comment by Lexiebean** [comment]
That's outside of the scope of what I want to achieve with this addon and I try to avoid feature bloat.

This would be very easy to write for another very similar addon.

ShaguChat should be able to do it actually really. With /sc bl _part of the text string that you wish to block_
